### PR TITLE
fix: ci build

### PR DESCRIPTION
**Pull request by okwasniewski**
This PR fixes the CI build to check if the build fail is caused by #124 or if is it failing in general

### CODE REVIEW

**Comment by wcandillon** [comment]
@okwasniewski I think it's because I ran over my github credits 🥲

**Comment by okwasniewski** [comment]
> @okwasniewski I think it's because I ran over my github credits 🥲

@wcandillon Yeah, that's the case 😅 But we don't need these more expensive workers for this build so its fine to use normal ones. I changed the workers on my other PR and it was still failing. I want to check if this is failing because of my PR or there is a general build issue on the CI

**Comment by okwasniewski** [comment]
@wcandillon the build is green I guess we can merge it and I will figure out what breaks it in my other PR. WDYT?

**Comment by wcandillon** [comment]
yes 🫡 Sorry we've been slow with the other PRs it's just that we are working on fixing substancial bugs in canvas API and I I would be more at ease if these would be merged to test the other PRs

**Review by wcandillon — APPROVED** [review]

**Pull request merged**
